version: '3'

services:
  db:
    image: mariadb:10.4.10-bionic
    volumes:
      - 'wordpressdb_data:/var/lib/mysql'
    ports:
        - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
      - MYSQL_ROOT_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
    networks:
      - default
  wordpress:
    build: './wordpress'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - wordpress_data:/bitnami
    depends_on:
      - db
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DEBUG=1
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
      - APP_URL=112.150.189.246:5000
    networks:
      - default

networks:
  default:

volumes:
  answerdb_data:
    driver: local
  wordpressdb_data:
    driver: local
  wordpress_data:
    driver: local
