version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password

  wordpress:
    depends_on:
      - db
    image: wordpress:5.2.4-php7.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    secrets:
      - db_password

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.17.5-alpine
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    
volumes:
  db_data: {}
  wordpress: {}

secrets:
  db_password:
    external: true