version: '3.4'

services:
  answerdb:
    image: mariadb:10.4.10-bionic
    volumes:
      - 'answerdb_data:/var/lib/mysql'
    hostname: answerdb
    environment:
      - MYSQL_DATABASE=answer
      - MYSQL_USER=answer
      - MYSQL_PASSWORD=4342b05a072f3d9c7c19f3e412326c8e
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  app:
    build: './app'
    depends_on:
      - answerdb
    environment:
      - MYSQL_HOST=answerdb
      - MYSQL_DATABASE=answer
      - MYSQL_USER=answer
      - MYSQL_PASSWORD=4342b05a072f3d9c7c19f3e412326c8e
  wordpressdb:
    image: mariadb:10.4.10-bionic
    volumes:
      - 'wordpressdb_data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - wordpressdb
    environment:
      - MARIADB_HOST=wordpressdb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=01d68185e332b1a6d61464991cf0d3c4

volumes:
  answerdb_data:
    driver: local
  wordpressdb_data:
    driver: local
  wordpress_data:
    driver: local
