version: '3'

services:
  db:
    image: mariadb:10.4.10-bionic
    volumes:
      - 'wordpressdb_data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
      - MYSQL_ROOT_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
    networks:
      - default
  wordpress:
    build: './wordpress'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - wordpress_data:/bitnami
    depends_on:
      - db
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
      - APP_URL=112.150.189.246:5000
    networks:
      - default
  prepare:
    image: wordpress:cli
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=01d68185e332b1a6d61464991cf0d3c4
    command: |
      wp plugin install --path="/var/www/html" wordpress-seo
      wp plugin install --path="/var/www/html" bbpress
    networks:
      - default

networks:
  default:

volumes:
  answerdb_data:
    driver: local
  wordpressdb_data:
    driver: local
  wordpress_data:
    driver: local
